### PR TITLE
Adds `AdminConfig` to override app_title, logo_url in the templates.

### PR DESCRIPTION
**Pull request by hasansezertasan**
Check out the `changed files`, there is a good example.

Resolves: #349

### CODE REVIEW

**Review by jowilf — COMMENTED** [review]
I suggest creating another class, `AdminConfig`, and a method `get_admin_config`. What do you think?

**Comment by hasansezertasan** [comment]
> I suggest creating another class, `AdminConfig`, and a method `get_admin_config`. What do you think?

I'm working on it

**Review by jowilf — CHANGES_REQUESTED** [review]
Your changes look great. Please add `get_admin_config` to [auth_provider](https://github.com/jowilf/starlette-admin/blob/main/tests/auth_provider.py) and include a test case for it in [test_auth](https://github.com/jowilf/starlette-admin/blob/main/tests/test_auth.py). Thanks!

**Review by jowilf — APPROVED** [review]
Great, Thank you @hasansezertasan

**Pull request merged**
