### PR TITLE
Support translation for delete row action submit button text.

### PR DESCRIPTION
**Pull request by hasansezertasan**
I didn't do anything with the i18n commands like `compile` or `extract` because those were removed at #425.

### CODE REVIEW

**Comment by jowilf** [comment]
> because those were removed at https://github.com/jowilf/starlette-admin/pull/425.

They were removed because they(`Username` and `Password`)  had already been translated.

**Comment by hasansezertasan** [comment]
OK then I'll compile it and commit.

**Comment by hasansezertasan** [comment]
@jowilf It should be ready now. I have removed "fuzzy" translations and I didn't add any translations for Turkish.

**Comment by hasansezertasan** [comment]
Closing due to inactivity.

**Pull request closed without merging**
