### PR TITLE
Add screenshots

### PR DESCRIPTION
**Pull request by jowilf**

### CODE REVIEW

**Comment by aminalaee** [comment]
@jowilf I'm happy that you could re-use anything from my project SQLAdmin: https://github.com/aminalaee/sqladmin
I see some resemblance in UI, code and even documentation. That's absolutely fine, but giving credit to other people's work won't be a problem to your own project, that will just show the maturity of the community we're working in.

**Comment by jowilf** [comment]
@aminalaee Please see my response here -> https://www.reddit.com/r/Python/comments/xbz8jd/comment/io5p83b/?utm_source=share&utm_medium=web2x&context=3

**Comment by cpbotha** [comment]
@jowilf I tried to read that reddit post to understand the relationship between sqladmin and starlette-admin better, but it looks like you've delete the post and all of your comments.

Could you please point me at any other sources online explaining the relationship between the two projects? It looks like starlette-admin was largely based on sqladmin when it started, and now the two projects still overlap substantially, which is why it would help greatly to have some information describing what the different foci are of the two projects, so that users can make an informed choice.

**Comment by hasansezertasan** [comment]
> It looks like starlette-admin was based on sqladmin when it started.

If you mean "fork of" by "based on", wouldn't that be a license breach? Since SQLAdmin is licensed under the BSD-3 license, and starlette admin is licensed under the MIT license and doesn't include and NOTICE file or any notice in the license file.

If the case is only inspiration and nothing else, I don't see any problem about licensing. I myself am getting inspired by a lot of projects like SQLAdmin, Starlette Admin, Flask AppBuilder, and Flask Admin for my FastUI Admin project which is still in the planning phase.

**Comment by cpbotha** [comment]
@hasansezertasan please read this comment by @aminalaee on the archived reddit post at https://www.reddit.com/r/Python/comments/xbz8jd/comment/io5p83b/

> As the author of [sqladmin](https://github.com/aminalaee/sqladmin) this project looks a lot like a fork (at least for now). The code, documentation and also the UI look the same. Of course this is expected in the open-source, but at least a mention or a link to give credit to my work would've been nice.
> A few screenshots: ...

**Comment by hasansezertasan** [comment]
> @hasansezertasan please read the remaining parts (most important comments by @aminalaee ) of the reddit post linked above: https://www.reddit.com/r/Python/comments/xbz8jd/starletteadmin_simple_and_extensible_admin/ 

Well, I have already read it before commenting 🤓.

> Their opening comment was this:
> 
> > As the author of [sqladmin](https://github.com/aminalaee/sqladmin) this project looks a lot like a fork (at least for now). The code, documentation and also the UI look the same. Of course this is expected in the open-source, but at least a mention or a link to give credit to my work would've been nice.
> > A few screenshots: ...

@aminalaee says "project looks like a fork" and brings some sort of evidence (the screenshots) about the take. The author is respectible, very kind and doesn't bring up anything about licensing and seeks some credits but I just wanted to make sure and join the conversation.

**Comment by jowilf** [comment]
Hi @cpbotha,

I added a new section in the [README.md](https://github.com/jowilf/starlette-admin?tab=readme-ov-file#why-starlette-admin)

Also, @hasansezertasan has started a great discussion on feature comparisons between multiple admin interfaces at https://github.com/jowilf/starlette-admin/discussions/333.

**Pull request merged**
